package oops;

public class Exception1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

try
 {
  int[] myNumbers = {1, 2, 3};
  System.out.println(myNumbers[1]);
} 
catch
 (Exception e) {
  System.out.println("Something went wrong.");
}
	}

}
